### ISSUE TITLE
maps not rendering on android

### ISSUE THREAD

**Issue by grantiago** [SemanticMediaWiki/SemanticMaps#51]
Empty gray box.
"Loading map..."

Loads fine on desktop

Semantic Maps 3.2
Semantic MediaWiki 2.3.1
MediaWiki 1.26.2
MobileFrontend 1.0.0

android 5.0
kernal 3.4.0-4516970
firefox 44.0.2
chrome 47.0256.83
stock browser as well

**Comment by mwjames** [comment]
> MobileFrontend 1.0.0

Hopefully fixed with https://github.com/JeroenDeDauw/Maps/pull/110 (Maps ~3.5)

**Comment by JeroenDeDauw** [comment]
Can you verify the issue is still present when using Maps 3.5 and Semantic Maps 3.3?

**Comment by grantiago** [comment]
The version mentioned by  mwjames #110 fixed it.  All well. 
Version
MediaWiki 	1.26.2
PHP 	5.6.18 (cgi-fcgi)
MySQL 	5.5.48-cll	
Semantic Maps	3.2	
Semantic MediaWiki	2.3.1
Maps	3.5.0-alpha

**Comment by grantiago** [comment]
The version mentioned by  mwjames #110 fixed it.  All well. 
Version
MediaWiki 	1.26.2
PHP 	5.6.18 (cgi-fcgi)
MySQL 	5.5.48-cll	
Semantic Maps	3.2	
Semantic MediaWiki	2.3.1
Maps	3.5.0-alpha

**Comment by JeroenDeDauw** [comment]
\o/
